# 1. ビルドステージ
FROM golang:1.25-alpine AS builder

WORKDIR /app

# Go Modulesのキャッシュ利用のため先にgo.modだけコピー
COPY go.mod go.sum ./
# gitの設定を追加（Go Modulesの依存関係を解決するため）
RUN apk add --no-cache git
# Go Modulesの依存関係をダウンロード
RUN go mod download

# ソースコードをコピー
COPY . .

# バイナリをビルド（出力ファイル名はapp）
RUN CGO_ENABLED=0 GOOS=linux go build -tags timetzdata -o app

# 2. 実行ステージ
FROM alpine:latest

WORKDIR /root/

# 証明書追加（HTTPS使う場合に必要）
RUN apk --no-cache add ca-certificates

# ビルド済みバイナリをコピー
COPY --from=builder /app/app .

# ポート開放
EXPOSE 8080

# コンテナ起動時に実行
CMD ["./app"]
